backstage-plugin-firefly:
  - changed-files:
      - any-glob-to-any-file: ["plugins/firefly/**/*"]
backstage-plugin-firefly-backend:
  - changed-files:
      - any-glob-to-any-file: ["plugins/firefly-backend/**/*"]