# Configuration for Release Drafter GitHub Action
name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'maintenance'
      - 'chore'
      - 'documentation'
      - 'docs'

change-template: '- $TITLE by @$AUTHOR (#$NUMBER)'

template: |
  ## Changes
  
  $CHANGES
