# Backstage override configuration for your local development environment
firefly:
  periodicCheck:
    interval: 3600
    fetchSystems: true
    fetchResources: true
    filters:
      assetTypes:
        - aws_s3_bucket
        - aws_lambda_function
        - google_compute_subnetwork
      providerIds:
        - '094724549126'
        - 'devops-372014'