# Backstage override configuration for your local development environment
firefly:
  periodicCheck:
    interval: 3600
    importSystems: true
    importResources: true
    correlateByComponentName: true
    tagKeysIdentifiers:
      - environment
      - component
    filters:
      assetTypes:
        - aws_s3_bucket
        - aws_lambda_function
        - aws_db_cluster_snapshot
        - aws_rds_cluster_instance
        - aws_rds_cluster
        - aws_security_group
        - aws_rds_cluster_parameter_group
        - aws_db_parameter_group
        - aws_cloudwatch_log_group
        - aws_db_subnet_group
        - aws_iam_role
        - aws_iam_policy
        - aws_sqs_queue
        - google_compute_subnetwork
      providerIds:
        - '094724549126'
        - 'devops-372014'
        - '096103536687'
        - '381492263740'