name: Publish Package to NPM and Build and Push Docker Image

on:
  release:
    types: ["published"]

jobs:
  publish:
    runs-on: [self-hosted, "production"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: yarn install

      - name: Clean
        run: yarn clean

      - name: Get Latest Release Tag
        id: release_tag
        run: |
          RELEASE_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          VERSION=${RELEASE_TAG#v}
          echo "tag=$VERSION" >> $GITHUB_ENV

      - name: Update package.json files
        run: |
          # Update the version in the specified package.json files
          jq ".version = \"$tag\"" plugins/firefly/package.json > tmp.json && mv tmp.json plugins/firefly/package.json
          jq ".version = \"$tag\"" plugins/firefly-backend/package.json > tmp.json && mv tmp.json plugins/firefly-backend/package.json
        env:
          tag: ${{ env.tag }}

      - name: Compile TypeScript
        run: yarn tsc:full
      
      - name: Test
        run: yarn test
      
      - name: Build Packages
        run: yarn build:all

      - name: Publish Packages to NPM
        run: |
          echo "npmAuthToken: $NODE_AUTH_TOKEN" >> ../../.yarnrc.yml
          yarn workspaces foreach --all --parallel --no-private npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Image to ECR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packages/backend/Dockerfile
          push: true
          tags: |
            public.ecr.aws/firefly/backstage-plugin:${{ env.tag }}
            public.ecr.aws/firefly/backstage-plugin:latest