name: Tests
on:
  pull_request:
    types: [ "opened", "synchronize", "reopened" ]
  workflow_dispatch:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install Dependencies
        run: yarn install
      - name: Compile TypeScript
        run: yarn tsc:full
      - name: Lint
        run: yarn lint:all
      - name: Test
        run: yarn test
      - name: Build Packages
        run: yarn build:all